name: Branch_alpha
on:
  push:
    branches: 
     - branch_alpha

jobs:
  init_project:
    name: My Second CI Test Script
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: https://api.github.com/repos/${{github.repository}}/issues
      URL_ROOT: https://github.com/${{github.repository}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
            go-version: 1.15

      - name: run proj
        run: go run .

      - name: at false
        if: ${{failure()}}
        run: |
          msg="content body:\n"$STEPS_CONTEXT
          echo $msg
          echo $JOB_CONTEXT
          echo $MATRIX_CONTEXT
          echo $GITHUB_CONTEXT
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{secrets.FIRST_CI_SCRT}}" \
          ${{env.ISSUE_URL}} \
          -d '{"title":"test false ${{github.event.head_commit.message}}", "body": "[查看问题](${{env.URL_ROOT}}/actions/runs/${{github.run_id}})", "assignees": ["${{github.event.head_commit.author.email}}"]}'
