# This is a basic workflow to help you get started with Actions

name: Branch_alpha_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
     - branch_alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init_project:
    name: My Second CI Test Script
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      branch_name: ${git rev-parse --abbrev-ref HEAD}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        run: echo $branch_name
