# This is a basic workflow to help you get started with Actions

name: Branch_alpha_pull_request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
     - branch_alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init_project:
    name: My Third CI Test Script
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PULL_ACTION: https://api.github.com/repos/${{github.repository}}/check-runs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: to  mark start
        run: |
          set -x
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          $PULL_ACTION \
          -d '{"name":"pr unit test","head_sha":"${{github.sha}}"}'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
            # The Go version to download (if necessary) and use. Supports semver spec and ranges.
            go-version: 1.15

      - name: run proj
        run: go run .
          
  try_another_job:
    name: New Job Test
    runs-on: ubuntu-latest
    needs: init_project
    if: ${{success()}}
    env:
      PULL_ACTION: https://api.github.com/repos/${{github.repository}}/check-runs
    steps:
      - name: to mark success
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{secrets.FIRST_CI_SCRT}}" \
          $PULL_ACTION \
          -d '{"name":"pr unit test","head_sha":"${{github.sha}}", "status":"completed", "conclusion":"success"}'
  try_first_false:
    name: New Job Test
    runs-on: ubuntu-latest
    needs: init_project
    if: ${{failure()}}
    env:
      PULL_ACTION: https://api.github.com/repos/${{github.repository}}/check-runs
    steps:
      - name: mark failure
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{ secrets.FIRST_CI_SCRT }}" \
          $PULL_ACTION \
          -d '{"name":"pr unit test","head_sha":"${{github.sha}}", "status":"completed", "conclusion":"failure"}'
