name: Branch_alpha
on:
  push:
    branches: 
     - branch_alpha

jobs:
  init_project:
    name: My Second CI Test Script
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: https://api.github.com/repos/${{github.repository}}/issues

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
            go-version: 1.15

      - name: run proj
        run: go run .

      - name: at false
        if: ${{failure()}}
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          msg="content body:\n"$STEPS_CONTEXT
          echo $msg
          echo $JOB_CONTEXT
          echo $MATRIX_CONTEXT
          echo $GITHUB_CONTEXT
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{secrets.FIRST_CI_SCRT}}" \
          https://api.github.com/repos/SimingLiu/simpletools/issues \
          -d '{"title":"测试", "body": "${{env.msg}}"}'
