# This is a basic workflow to help you get started with Actions

name: Branch_alpha_pull_request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
     - branch_alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init_project:
    name: My Third CI Test Script
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PULL_ACTION: https://api.github.com/repos/${{github.repository}}/check-runs
      branch_name: ${git rev-parse --abbrev-ref HEAD}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: to  mark start
        run: echo $branch_name
