# This is a basic workflow to help you get started with Actions

name: Branch_alpha_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
     - branch_alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init_project:
    name: My Second CI Test Script
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: first step
        env:
          IS_PUSH: ${{endsWith($GITHUB_EVENT_NAME, 'push')}}
        run: |
          import os
          if "GITHUB_REF" in os.environ:
            print(os.getenv("GITHUB_REF"))
          else:
            print("no $GITHUB_REF found")
          print("now push=", os.getenv("IS_PUSH"))
        shell: python

      - name: checkout code
        if: ${{github.event_name}} == "push" && ${{success()}}
        run: echo $GITHUB_REF
          
